[package]
name = "chachablake3"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zeroize = "1.6"
aead = "0.5.2"
blake3 = "1.3.3"
chacha20 = "0.9.1"